title: Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: Title
              instructions_position: above
              listable: true
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
          -
            handle: icon
            field:
              input_type: text
              default: '<i class="bi bi-briefcase"></i>'
              antlers: false
              type: text
              display: iCon
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: content
            field:
              antlers: false
              type: textarea
              display: Content
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: section_heading
            field:
              input_type: text
              default: 'Services List'
              antlers: false
              type: text
              display: 'Section Heading'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: services
            field:
              fields:
                -
                  handle: service
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: Service
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
              mode: table
              reorderable: true
              fullscreen: true
              type: grid
              display: Services
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: image
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Image
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: service_description
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: 'Service Description'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              hide_partials: true
              blueprint: false
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - 'max:200'
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              from: title
              generate: true
              show_regenerate: false
              hide_display: false
  seo:
    display: SEO
    sections:
      -
        display: 'New Section'
        fields:
          -
            handle: meta_title
            field:
              input_type: text
              default: 'Transform Your Website with Custom WordPress Development'
              antlers: false
              type: text
              display: 'Meta Title'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: meta_description
            field:
              default: 'Expert Web Development Services: Custom Solutions, Responsive Design, E-commerce Integration, Web Applications, and Ongoing Support. Transform Your Online Presence with Our Innovative Approach, Technical Expertise, and Collaborative Spirit. Elevate Your Business with Our Comprehensive Web Development Services'
              antlers: false
              type: textarea
              display: 'Meta Description'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: meta_tags
            field:
              default: 'web development, custom web design, responsive web development, website development services, eCommerce web development, SEO-friendly web design, front-end development, back-end development, full-stack development, professional web developers, web design company, digital solutions, website optimization, user experience design, web development Concrete5, Concrete5 CMS services, Concrete5 website design, custom Concrete5 themes, Concrete5 CMS development, Concrete5 web development solutions, Concrete5 site customization, Concrete5 SEO optimization, Concrete5 CMS experts, Concrete5 development company, Concrete5 web design services, Concrete5 user-friendly websites, Concrete5 eCommerce solutions, Concrete5 CMS support,WordPress web development, custom WordPress design, WordPress CMS services, WordPress theme development, WordPress plugin development, responsive WordPress websites, SEO-friendly WordPress design, WordPress site optimization, WordPress development company, professional WordPress developers, WordPress eCommerce solutions, WordPress website support, WordPress site customization, WordPress web design services'
              antlers: false
              type: textarea
              display: 'Meta Tags'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
